# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
git:
  short_hash: true
builds:
- goos:
  - linux
  - darwin
  - windows
  goarch:
  - "386"
  - arm64
- env:
  - CGO_ENABLED=0
archive:
  format_overrides:
    - goos: windows
      format: zip
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'
snapshot:
  name_template: "SNAPSHOT-{{ .Commit }}"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - '^scripts:'
    - '^fixture:'
