default_env: &default_env
  docker:
    - image: circleci/golang:1.10.3
  working_directory: /go/src/github.com/jmatsu/dpg

version: 2
jobs:
  on_every_commit:
    <<: *default_env
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go test -v ./...
      - run: ./scripts/make_diff_by_go-fmt
  update_docs:
    <<: *default_env
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - add_ssh_keys:
          fingerprints:
            - "d4:0c:e7:da:b8:f8:c3:93:53:99:24:9b:fa:71:42:d9"
      - run: |
          go build # make sure the version of the used binary
          PATH=$PWD:$PATH ./scripts/update_README.bash
  release:
    <<: *default_env
    steps:
      - checkout
      - run:
      - run: curl -sL https://git.io/goreleaser | bash
      - run: go get -v -t -d ./...
      - run: goreleaser

workflows:
  version: 2
  every_branch:
    jobs:
      - on_every_commit
  on_master:
    jobs:
      - update_docs:
          filters:
            branches:
              only: /master/
  release_binary:
    jobs:
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
